name: Deploy Infrastructure

on:
  push:
    branches:
      - main
      - devops

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        working-directory: ./terraform
        id: tfplan
        run: terraform plan -var app_name=ordering_app -var rds_instance_name=ordering-app-rds -out=tfplan

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
